version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install -r requirements.txt

python:
  install:
    - requirements: requirements.txt