version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true


build:
  jobs:
    pre_build:
      - sphinx-build -b html docs/source docs/_build/html

python:
  install:
    - method: pip
      path: .